modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="spawners_craft"
version="1.1.0"
displayName="Spawners Craft"
credits="https://www.mcmod.cn/author/26620.html"
displayURL="https://center.mcmod.cn/91492/"
logoFile="logo.png"
authors="xia_xin"

[[dependencies.spawners_craft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




